apiVersion: v1
kind: ConfigMap
metadata:
  name: owui-socle-config
  namespace: ${NAMESPACE}
data:
  SCW_LLM_BASE_URL: "${SCW_LLM_BASE_URL}"
  SCW_LLM_MODEL: "${SCW_LLM_MODEL}"
  OPENAI_EMBEDDING_MODEL: "${OPENAI_EMBEDDING_MODEL}"
  OPENWEBUI_PUBLIC_URL: "https://${OPENWEBUI_HOST}"
  KEYCLOAK_PUBLIC_URL: "https://${KEYCLOAK_HOST}"
  KEYCLOAK_INTERNAL_URL: "http://keycloak"
  KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
  OPENWEBUI_HOST: "${OPENWEBUI_HOST}"
  KEYCLOAK_HOST: "${KEYCLOAK_HOST}"
  SEARXNG_HOST: "${SEARXNG_HOST}"
  SEARXNG_BASE_URL: "http://searxng"
  OPENID_PROVIDER_URL: "https://${KEYCLOAK_HOST}/realms/openwebui/.well-known/openid-configuration"
  ANEF_API_BASE: "http://anef-pj-knowledge-assistant"
  ANEF_PUBLIC_BASE: "http://anef-pj-knowledge-assistant"
