apiVersion: v1
kind: Secret
metadata:
  name: grafrag-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  SCW_SECRET_KEY_LLM: CHANGE_ME
  SCW_API_KEY: CHANGE_ME
  PIPELINES_API_KEY: CHANGE_ME
  WEBUI_SECRET_KEY: CHANGE_ME
  SEARXNG_SECRET: CHANGE_ME
  KEYCLOAK_ADMIN_PASSWORD: CHANGE_ME
  KEYCLOAK_CLIENT_SECRET: CHANGE_ME
  GRAPHRAG_CACHE_S3_ACCESS_KEY_ID: CHANGE_ME
  GRAPHRAG_CACHE_S3_SECRET_ACCESS_KEY: CHANGE_ME
  GRAPHRAG_CACHE_S3_SESSION_TOKEN: ""
